version: '2'
services:
    springwebsockets-app:
        image: springwebsockets
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=springwebsockets-cassandra
            - JHIPSTER_SLEEP=30 # gives time for the Cassandra cluster to start and execute the migration scripts
        ports:
            - 8080:8080
    springwebsockets-cassandra:
        extends:
            file: cassandra-cluster.yml
            service: springwebsockets-cassandra
    springwebsockets-cassandra-node:
        image: cassandra:3.9
        environment:
            - CASSANDRA_SEEDS=springwebsockets-cassandra
    springwebsockets-cassandra-migration:
        extends:
            file: cassandra-migration.yml
            service: springwebsockets-cassandra-migration
        environment:
            - CREATE_KEYSPACE_SCRIPT=create-keyspace-prod.cql
